In [2]:
import pandas as pd
import numpy as np

X_train1 = np.load('../Task_4_data/X_train.npy')
X_test1 = np.load('../Task_4_data/X_test.npy')
y_train1 = np.load('../Task_4_data/y_train.npy')
y_test1 = np.load('../Task_4_data/y_test.npy')

print(X_train1.shape)
print(X_test1.shape)
print(y_train1.shape)
print(y_test1.shape)

(9000, 3)
(3000, 3)
(9000,)
(3000,)


In [6]:
X_train=np.empty((0,1500))
y_train=y_train1[0:9000:500]
for i in range(0,9000,500):
    X_train=np.vstack((X_train,np.hstack([X_train1[i:i+500,0],X_train1[i:i+500,1],X_train1[i:i+500,2]])))
print(X_train.shape)
print(y_train.shape)

print(X_train)
print(y_train)

(18, 1500)
(18,)
[[-0.2018 -0.3225 -0.2937 ... -0.0911 -0.0989 -0.1062]
 [ 0.0963  0.0933 -0.0127 ... -0.1712 -0.1839 -0.1898]
 [-0.1344 -0.1339 -0.0503 ... -0.2802  0.1356  0.1415]
 ...
 [ 0.1779  0.1955  0.1774 ...  0.1386  0.1517  0.1601]
 [-0.0215 -0.0176 -0.04   ... -0.1195 -0.1229 -0.1356]
 [-0.0396 -0.0366 -0.0366 ...  1.0014  1.0019  1.0024]]
[1 2 3 4 5 6 1 2 3 4 5 6 1 2 3 4 5 6]


In [5]:
X_test=np.empty((0,1500))
y_test=y_test1[0:3000:500]
for i in range(0,3000,500):
    X_test=np.vstack((X_test,np.hstack([X_test1[i:i+500,0],X_test1[i:i+500,1],X_test1[i:i+500,2]])))
print(X_test.shape)
print(y_test.shape)

(6, 1500)
(6,)


In [9]:
filename = 'finalized_dt_model.sav'
import pickle
# load the model from disk
dt2 = pickle.load(open(filename, 'rb'))


In [10]:

# Extract features using TSFEL
import tsfel
import sklearn

cfg = tsfel.get_features_by_domain()  # Get all features by default
X_train_real_tsfel = tsfel.time_series_features_extractor(cfg,X_train, verbose=1,fs =50)
X_test_real_tsfel = tsfel.time_series_features_extractor(cfg,X_test, verbose=1,fs =50)

y_test_real_tsfel = y_test
y_train_real_tsfel = y_train

print(f"X_train_tsfel: {X_train_real_tsfel.shape}")
print(f"X_test_tsfel: {X_test_real_tsfel.shape}")
print(f"y_train: {y_train.shape}")
print(f"y_test: {y_test.shape}")


y_tsfel_pred=dt2.predict(X_test_real_tsfel)

print("Accuracy: ",sklearn.metrics.accuracy_score(y_test_real_tsfel, y_tsfel_pred))
print("Precision: ",sklearn.metrics.precision_score(y_test_real_tsfel, y_tsfel_pred,average='macro'))
print("Recall: ",sklearn.metrics.recall_score(y_test_real_tsfel, y_tsfel_pred,average='macro'))

comparison_df = pd.DataFrame({
    'True Label': y_test,
    'Predicted Label': y_tsfel_pred
})

# Display the DataFrame
display(comparison_df)

*** Feature extraction started ***



*** Feature extraction finished ***
*** Feature extraction started ***


ValueError: Input signal must have a length >= n_coeff